### PR TITLE
FDC3 fix expecting of iframes to always have glue window

### LINKED ISSUE #711: [BUG] Error thrown when calling `addContextListener` from an iframe
**Describe the bug**

We have a web platform loading apps inside iframes. 
When an app is calling `addContextListener`, the following error is thrown:

```
this.glue.windows.my(...).getContext is not a function
    at GlueController.getContextForMyWindow (fdc3.umd.js:1109:43)
    at ChannelsController.<anonymous> (fdc3.umd.js:2391:65)
    at Generator.next (<anonymous>)
    at fdc3.umd.js:40:75
    at new Promise (<anonymous>)
    at __awaiter (fdc3.umd.js:36:16)
    at ChannelsController.handleWindowContextOnOpening (fdc3.umd.js:2390:20)
    at ChannelsController.<anonymous> (fdc3.umd.js:2167:26)
    at Generator.next (<anonymous>)
    at fulfilled (fdc3.umd.js:37:62)
```

Note the error also occurs when subsequently calling `joinUserChannel`.

**To Reproduce**

With `addContextListener`

1. Create a glue enabled app, and call `addContextListener` on fdc3 ready
2. Create a web platform, and add an iframe pointing to the app created at step 1

With `joinUserChannel`

1. Create a glue enabled app, call `addContextListener` on fdc3 ready and add a button to call `joinUserChannel`
2. Create a web platform, and add an iframe pointing to the app created at step 1
3. Click on the button to join user channel

**Expected behavior**

No error should be thrown

**Code Sample**

[Here is a sample project reproducing the issue](https://codesandbox.io/s/zen-sanne-o18os0?file=/index.html)

**Desktop (please complete the following information):**
* Glue Version: 
    * @glue42/web-platform@**1.24.3**
    * @glue42/web@**2.19.1**
    *  @glue42/fdc3@**3.2.0**
* OS: MacOS 11.2.3
* Browser Chrome (Version 112)

**Additional context**

### PR DESCRIPTION
**Pull request by ksgeorgieva**
Fix expecting of `glue.windows.my()` to always be defined since iframes in non-glue windows do not have window. 
Add new support app with glue-enabled iframe in it for testing with control methods. 
Implement tests to validate fix. 

Closes #711

### CODE REVIEW

File: packages/fdc3/src/controllers/glue.ts [hunk 1]
```diff
@@ -157,12 +157,8 @@ export class GlueController {
         return this.glue.channels.get(channelId);
     }
 
-    public getContextForMyWindow(): Promise<any> {
-        return this.glue.windows.my().getContext();
-    }
-
-    public getMyWindowId(): string {
-        return this.glue.windows.my().id;
+    public getMyWindow(): GDWindow | Record<string, never> {
```
Comment (flashd2n) [inline packages/fdc3/src/controllers/glue.ts:160]: Why Record instead of GDWindow | undefined? Here we can also do the check if the obj is empty, aka no window and return void in that case.

**Review by flashd2n — CHANGES_REQUESTED** [review]

**Review by flashd2n — APPROVED** [review]
